CREATE DATABASE open1sum;

CREATE TABLE IF NOT EXISTS products (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    price DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT product_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS reviews (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    author VARCHAR(255) NOT NULL,
    rating SMALLINT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    product_id INT NOT NULL,

    CONSTRAINT review_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS summaries (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    product_id INT NOT NULL,
    content TEXT NOT NULL,
    generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMPTZ NOT NULL,
    
    CONSTRAINT summary_pkey PRIMARY KEY (id)
);

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS summary_product_id_key ON summaries(product_id);

-- AddForeignKey (Fixed "review" to "reviews")
ALTER TABLE reviews ADD CONSTRAINT review_product_id_fkey 
    FOREIGN KEY (product_id) REFERENCES products(id) 
    ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE summaries ADD CONSTRAINT summary_product_id_fkey 
    FOREIGN KEY (product_id) REFERENCES products(id) 
    ON DELETE RESTRICT ON UPDATE CASCADE;


